version: 2
models:
  - name: stg_customers
    description: incoming streaming data on customer attributes related to their orders
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
  - name: stg_payments
    columns: 
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_id